// Master Action Registry for NEO Human Motor Actions
import { ActionDefinition, RobotAction } from '../../types/robot';

export const ACTION_REGISTRY: Record<RobotAction, ActionDefinition> = {
  // === 1. BASIC LOCOMOTION & NAVIGATION ===
  walk_forward: {
    id: 'walk_forward',
    name: 'Walk Forward',
    category: 'locomotion',
    layer: 'full_body',
    duration: 3500,
    isLooping: true,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Stepping forward! On the move.',
    description: 'Travels forward across the 3D space with natural alternating leg stride and counter arm swing.',
  },
  walk_backward: {
    id: 'walk_backward',
    name: 'Walk Backward',
    category: 'locomotion',
    layer: 'full_body',
    duration: 3500,
    isLooping: true,
    interruptible: true,
    emotion: 'neutral',
    replyDialogue: 'Stepping backward carefully.',
    description: 'Travels backward in world space with reverse gait mechanics.',
  },
  walk_left: {
    id: 'walk_left',
    name: 'Walk Left',
    category: 'locomotion',
    layer: 'full_body',
    duration: 3000,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Walking over to the left side.',
    description: 'Navigates and travels toward the left side of the virtual room.',
  },
  walk_right: {
    id: 'walk_right',
    name: 'Walk Right',
    category: 'locomotion',
    layer: 'full_body',
    duration: 3000,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Walking over to the right side.',
    description: 'Navigates and travels toward the right side of the virtual room.',
  },
  turn_left: {
    id: 'turn_left',
    name: 'Turn Left 90°',
    category: 'locomotion',
    layer: 'full_body',
    duration: 1800,
    isLooping: false,
    interruptible: true,
    emotion: 'neutral',
    replyDialogue: 'Turning to the left.',
    description: 'Performs in-place body rotation 90 degrees left with stepping foot alignment.',
  },
  turn_right: {
    id: 'turn_right',
    name: 'Turn Right 90°',
    category: 'locomotion',
    layer: 'full_body',
    duration: 1800,
    isLooping: false,
    interruptible: true,
    emotion: 'neutral',
    replyDialogue: 'Turning to the right.',
    description: 'Performs in-place body rotation 90 degrees right with stepping foot alignment.',
  },
  rotate_180: {
    id: 'rotate_180',
    name: 'Turn Around 180°',
    category: 'locomotion',
    layer: 'full_body',
    duration: 2400,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: 'Turning around to check behind!',
    description: 'Smooth 180-degree half-turn rotation.',
  },
  rotate_360: {
    id: 'rotate_360',
    name: 'Full Spin 360°',
    category: 'locomotion',
    layer: 'full_body',
    duration: 2800,
    isLooping: false,
    interruptible: true,
    emotion: 'excited',
    replyDialogue: 'Spinning 360 degrees!',
    description: 'Smooth full 360-degree rotation.',
  },
  stop: {
    id: 'stop',
    name: 'Stop Movement',
    category: 'locomotion',
    layer: 'full_body',
    duration: 800,
    isLooping: false,
    interruptible: true,
    emotion: 'neutral',
    replyDialogue: 'Halting all motion. Standing by!',
    description: 'Smoothly decelerates locomotion and settles into balanced idle pose.',
  },
  approach_target: {
    id: 'approach_target',
    name: 'Approach (Come Closer)',
    category: 'locomotion',
    layer: 'full_body',
    duration: 2800,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Coming right over to you!',
    description: 'Walks forward to approach the user camera.',
  },
  move_away: {
    id: 'move_away',
    name: 'Step Back',
    category: 'locomotion',
    layer: 'full_body',
    duration: 2400,
    isLooping: false,
    interruptible: true,
    emotion: 'neutral',
    replyDialogue: 'Stepping back a bit.',
    description: 'Steps back away from the user camera.',
  },
  follow_target: {
    id: 'follow_target',
    name: 'Follow Target',
    category: 'locomotion',
    layer: 'full_body',
    duration: 0,
    isLooping: true,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: 'Following your movements!',
    description: 'Continuous target following mode tracking cursor position.',
  },
  look_at_target: {
    id: 'look_at_target',
    name: 'Look at Target',
    category: 'locomotion',
    layer: 'head_face',
    duration: 2000,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: "I'm looking right at you!",
    description: 'Focuses head and eyes directly on the user or cursor.',
  },
  walk_center: {
    id: 'walk_center',
    name: 'Return to Center',
    category: 'locomotion',
    layer: 'full_body',
    duration: 2400,
    isLooping: false,
    interruptible: true,
    emotion: 'neutral',
    replyDialogue: 'Returning to the center position.',
    description: 'Walks back to world origin [0, 0, 0].',
  },
  reset_position: {
    id: 'reset_position',
    name: 'Reset Position',
    category: 'locomotion',
    layer: 'full_body',
    duration: 1500,
    isLooping: false,
    interruptible: true,
    emotion: 'neutral',
    replyDialogue: 'Position reset to center.',
    description: 'Resets position, orientation, and pose to resting defaults.',
  },

  // === 2. HAND AND ARM ACTIONS ===
  wave: {
    id: 'wave',
    name: 'Wave Hello',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3800,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    eyeExpression: 'happy_crescents',
    replyDialogue: 'Hello there, Razaq! Waving right at you!',
    description: 'High-energy overhead hand wave with wrist rotation and cheerful posture.',
  },
  wave_hello: {
    id: 'wave_hello',
    name: 'Wave Hello',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3800,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    eyeExpression: 'happy_crescents',
    replyDialogue: 'Hi Razaq! So happy to see you!',
    description: 'Enthusiastic greeting wave.',
  },
  wave_goodbye: {
    id: 'wave_goodbye',
    name: 'Wave Goodbye',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 4000,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    eyeExpression: 'happy_crescents',
    replyDialogue: 'Goodbye! See you very soon, Razaq!',
    description: 'Double-hand friendly farewell wave with swaying head.',
  },
  raise_left_hand: {
    id: 'raise_left_hand',
    name: 'Raise Left Hand',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 2600,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Left hand raised high!',
    description: 'Raises left arm overhead.',
  },
  raise_right_hand: {
    id: 'raise_right_hand',
    name: 'Raise Right Hand',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 2600,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Right hand raised up!',
    description: 'Raises right arm overhead.',
  },
  raise_both_hands: {
    id: 'raise_both_hands',
    name: 'Raise Both Hands',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3200,
    isLooping: false,
    interruptible: true,
    emotion: 'excited',
    replyDialogue: 'Hooray! Both hands up!',
    description: 'Raises both arms high in celebratory gesture.',
  },
  point_left: {
    id: 'point_left',
    name: 'Point Left',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 2800,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: 'Look over there to the left!',
    description: 'Extends left arm and points index finger left.',
  },
  point_right: {
    id: 'point_right',
    name: 'Point Right',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 2800,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: 'Pointing to the right side.',
    description: 'Extends right arm and points index finger right.',
  },
  point_forward: {
    id: 'point_forward',
    name: 'Point Forward',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 2800,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: 'Pointing directly at you!',
    description: 'Points index finger forward toward user.',
  },
  point_upward: {
    id: 'point_upward',
    name: 'Point Upward',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3000,
    isLooping: false,
    interruptible: true,
    emotion: 'excited',
    replyDialogue: 'Look up! The sky is the limit!',
    description: 'Iconic reference pose: Points index finger straight up toward the sky.',
  },
  thumbs_up: {
    id: 'thumbs_up',
    name: 'Thumbs Up',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3000,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    eyeExpression: 'happy_crescents',
    replyDialogue: 'Thumbs up, Razaq! You did great!',
    description: 'Extends arm forward and makes thumbs-up fist gesture with nod.',
  },
  clap: {
    id: 'clap',
    name: 'Clap Hands',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3600,
    isLooping: false,
    interruptible: true,
    emotion: 'excited',
    eyeExpression: 'happy_crescents',
    replyDialogue: 'Bravo! Clapping for you!',
    description: 'Brings hands together in front of chest in rhythmic applause.',
  },
  cross_arms: {
    id: 'cross_arms',
    name: 'Cross Arms',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 4000,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: 'Crossing arms in cool mode!',
    description: 'Folds both arms across chest in a confident stance.',
  },
  stretch_arms: {
    id: 'stretch_arms',
    name: 'Stretch Arms',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3500,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Ahhh! A nice refreshing stretch!',
    description: 'Extends arms wide horizontally to stretch.',
  },
  reach_forward: {
    id: 'reach_forward',
    name: 'Reach Forward',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3000,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: 'Reaching out forward!',
    description: 'Extends both arms forward with open palms.',
  },
  reach_upward: {
    id: 'reach_upward',
    name: 'Reach Upward',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3200,
    isLooping: false,
    interruptible: true,
    emotion: 'excited',
    replyDialogue: 'Reaching for the stars!',
    description: 'Stretches both arms high upward.',
  },
  handshake: {
    id: 'handshake',
    name: 'Handshake Gesture',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3500,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Nice to meet you! Let us shake hands!',
    description: 'Extends right hand forward with rhythmic up/down handshake pumping.',
  },
  present_object: {
    id: 'present_object',
    name: 'Present / Offer',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3400,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Here you go! Presenting this for you!',
    description: 'Extends palms forward in a presentation gesture.',
  },
  beckon: {
    id: 'beckon',
    name: 'Beckon (Come Closer)',
    category: 'hand_arm',
    layer: 'upper_body',
    duration: 3200,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: 'Come over here! Check this out!',
    description: 'Curles hand inward inviting the user closer.',
  },

  // === 3. BODY ACTIONS ===
  bow: {
    id: 'bow',
    name: 'Polite Bow',
    category: 'body',
    layer: 'full_body',
    duration: 3200,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'It is an honor to assist you, Razaq.',
    description: 'Bends torso forward 35 degrees with arms neatly at sides in respectful bow.',
  },
  nod: {
    id: 'nod',
    name: 'Nod Head',
    category: 'body',
    layer: 'head_face',
    duration: 1600,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Yes, absolutely!',
    description: 'Double head nod in agreement.',
  },
  shake_head: {
    id: 'shake_head',
    name: 'Shake Head',
    category: 'body',
    layer: 'head_face',
    duration: 1800,
    isLooping: false,
    interruptible: true,
    emotion: 'confused',
    replyDialogue: 'Nope, no problem at all!',
    description: 'Side-to-side head shake in disagreement.',
  },
  tilt_head: {
    id: 'tilt_head',
    name: 'Tilt Head',
    category: 'body',
    layer: 'head_face',
    duration: 2200,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: 'Hmm, tell me more!',
    description: 'Inquisitive head tilt to one side.',
  },
  lean_forward: {
    id: 'lean_forward',
    name: 'Lean Forward',
    category: 'body',
    layer: 'full_body',
    duration: 2800,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: "I'm listening closely!",
    description: 'Leans upper torso forward inquisitively.',
  },
  lean_backward: {
    id: 'lean_backward',
    name: 'Lean Backward',
    category: 'body',
    layer: 'full_body',
    duration: 2800,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Relaxing back a bit.',
    description: 'Leans torso backward in relaxed posture.',
  },
  turn_torso: {
    id: 'turn_torso',
    name: 'Turn Torso',
    category: 'body',
    layer: 'upper_body',
    duration: 2600,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: 'Twisting to take a look!',
    description: 'Rotates upper spine while hips stay anchored.',
  },
  crouch: {
    id: 'crouch',
    name: 'Crouch',
    category: 'body',
    layer: 'full_body',
    duration: 3000,
    isLooping: false,
    interruptible: true,
    emotion: 'neutral',
    replyDialogue: 'Crouching down into low stance.',
    description: 'Bends knees and lowers pelvis into athletic crouch.',
  },
  sit: {
    id: 'sit',
    name: 'Sit Down',
    category: 'body',
    layer: 'full_body',
    duration: 0,
    isLooping: true,
    interruptible: true,
    emotion: 'neutral',
    replyDialogue: 'Taking a comfortable seat.',
    description: 'Sits down with legs bent 90 degrees.',
  },
  sit_down: {
    id: 'sit_down',
    name: 'Sit Down',
    category: 'body',
    layer: 'full_body',
    duration: 0,
    isLooping: true,
    interruptible: true,
    emotion: 'neutral',
    replyDialogue: 'Sitting down and chilling with you.',
    description: 'Sits down posture.',
  },
  stand_up: {
    id: 'stand_up',
    name: 'Stand Up',
    category: 'body',
    layer: 'full_body',
    duration: 2000,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Standing up on my feet!',
    description: 'Transitions from sitting/crouching back to upright stance.',
  },
  jump: {
    id: 'jump',
    name: 'High Jump',
    category: 'body',
    layer: 'full_body',
    duration: 3200,
    isLooping: false,
    interruptible: true,
    emotion: 'excited',
    eyeExpression: 'wide_excited',
    replyDialogue: 'Boing! Thrusters engaged! High jump!',
    description: 'Crouch anticipation, high vertical leap into the air with tucked legs, and soft squash landing.',
  },
  celebrate: {
    id: 'celebrate',
    name: 'Celebrate',
    category: 'body',
    layer: 'full_body',
    duration: 4500,
    isLooping: false,
    interruptible: true,
    emotion: 'excited',
    eyeExpression: 'happy_crescents',
    replyDialogue: 'Woohoo! Victory celebration! You rock, Razaq!',
    description: 'Joyous multi-hop celebration with raised waving arms.',
  },
  dance: {
    id: 'dance',
    name: 'Party Dance',
    category: 'body',
    layer: 'full_body',
    duration: 6500,
    isLooping: false,
    interruptible: true,
    emotion: 'excited',
    eyeExpression: 'happy_crescents',
    replyDialogue: 'Check out these robotic dance moves!',
    description: 'Full coordinated dance routine with hip sways, alternating arm pumps, body twirls, and head bops.',
  },
  sleep: {
    id: 'sleep',
    name: 'Sleep Mode',
    category: 'body',
    layer: 'full_body',
    duration: 0,
    isLooping: true,
    interruptible: true,
    emotion: 'sleepy',
    eyeExpression: 'closed_sleep',
    replyDialogue: 'Entering sleep mode... Wake me anytime... Zzz.',
    description: 'Gentle floating posture, eyes closed, slow breathing motion.',
  },
  wake_up: {
    id: 'wake_up',
    name: 'Wake Up',
    category: 'body',
    layer: 'full_body',
    duration: 2500,
    isLooping: false,
    interruptible: true,
    emotion: 'surprised',
    eyeExpression: 'wide_excited',
    replyDialogue: 'Energized and online! Good morning, Razaq!',
    description: 'Waking up stretch with wide glowing eyes.',
  },

  // === 4. EXPRESSIVE ACTIONS ===
  happy: {
    id: 'happy',
    name: 'Happy',
    category: 'expressive',
    layer: 'full_body',
    duration: 3000,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    eyeExpression: 'happy_crescents',
    replyDialogue: 'Yay! I feel super happy!',
    description: 'Joyful body bounce with happy crescent eyes.',
  },
  curious: {
    id: 'curious',
    name: 'Curious',
    category: 'expressive',
    layer: 'upper_body',
    duration: 3000,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    eyeExpression: 'confused_asym',
    replyDialogue: 'Fascinating! What is that?',
    description: 'Inquisitive head tilt with asymmetrical questioning eyes.',
  },
  confused: {
    id: 'confused',
    name: 'Confused',
    category: 'expressive',
    layer: 'upper_body',
    duration: 3200,
    isLooping: false,
    interruptible: true,
    emotion: 'confused',
    eyeExpression: 'confused_asym',
    replyDialogue: 'Hmm, I am scratching my robotic head on that one!',
    description: 'Scratching head gesture with asymmetrical eyes.',
  },
  surprised: {
    id: 'surprised',
    name: 'Surprised',
    category: 'expressive',
    layer: 'full_body',
    duration: 2800,
    isLooping: false,
    interruptible: true,
    emotion: 'surprised',
    eyeExpression: 'wide_excited',
    replyDialogue: 'Whoa! That surprised my sensors!',
    description: 'Steps back with wide open eyes and raised hands.',
  },
  thinking: {
    id: 'thinking',
    name: 'Thinking',
    category: 'expressive',
    layer: 'upper_body',
    duration: 3500,
    isLooping: false,
    interruptible: true,
    emotion: 'thinking',
    eyeExpression: 'thinking_dart',
    replyDialogue: 'Analyzing the parameters... calculating...',
    description: 'Hand under chin in deep thought with darting eye expression.',
  },
  sad: {
    id: 'sad',
    name: 'Sad / Empathy',
    category: 'expressive',
    layer: 'full_body',
    duration: 3500,
    isLooping: false,
    interruptible: true,
    emotion: 'sad',
    eyeExpression: 'sad_droop',
    replyDialogue: 'I am right here with you. Everything will be okay.',
    description: 'Drooping shoulders and gentle downward gaze.',
  },
  excited: {
    id: 'excited',
    name: 'Excited',
    category: 'expressive',
    layer: 'full_body',
    duration: 3600,
    isLooping: false,
    interruptible: true,
    emotion: 'excited',
    eyeExpression: 'happy_crescents',
    replyDialogue: 'Yay! I am so excited!',
    description: 'Energetic hops and arm pumps.',
  },
  shy: {
    id: 'shy',
    name: 'Shy',
    category: 'expressive',
    layer: 'full_body',
    duration: 3200,
    isLooping: false,
    interruptible: true,
    emotion: 'shy',
    eyeExpression: 'happy_crescents',
    replyDialogue: 'Aww, you make my circuits blush!',
    description: 'Hands behind back with bashful head tilt.',
  },
  listening_attentively: {
    id: 'listening_attentively',
    name: 'Listening Attentively',
    category: 'expressive',
    layer: 'upper_body',
    duration: 0,
    isLooping: true,
    interruptible: true,
    emotion: 'curious',
    eyeExpression: 'wide_excited',
    replyDialogue: "I am listening to you closely, Razaq.",
    description: 'Turns forward, head slightly tilted, ears illuminated.',
  },
  laughing: {
    id: 'laughing',
    name: 'Laughing',
    category: 'expressive',
    layer: 'full_body',
    duration: 3500,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    eyeExpression: 'happy_crescents',
    replyDialogue: 'Haha! That is hilarious! Beep boop!',
    description: 'Torso shaking with laughter and head tilted back.',
  },

  // Legacy aliases
  come_closer: {
    id: 'come_closer',
    name: 'Come Closer',
    category: 'locomotion',
    layer: 'full_body',
    duration: 2800,
    isLooping: false,
    interruptible: true,
    emotion: 'happy',
    replyDialogue: 'Coming right over to you!',
    description: 'Approaches user.',
  },
  step_back: {
    id: 'step_back',
    name: 'Step Back',
    category: 'locomotion',
    layer: 'full_body',
    duration: 2400,
    isLooping: false,
    interruptible: true,
    emotion: 'neutral',
    replyDialogue: 'Stepping back.',
    description: 'Steps back.',
  },
  turn_around: {
    id: 'turn_around',
    name: 'Turn Around',
    category: 'locomotion',
    layer: 'full_body',
    duration: 2500,
    isLooping: false,
    interruptible: true,
    emotion: 'excited',
    replyDialogue: 'Spinning around!',
    description: 'Turn around.',
  },
  look_at_me: {
    id: 'look_at_me',
    name: 'Look at Me',
    category: 'locomotion',
    layer: 'head_face',
    duration: 2000,
    isLooping: false,
    interruptible: true,
    emotion: 'curious',
    replyDialogue: "Looking right at you!",
    description: 'Look at camera.',
  },
};

export const getActionDefinition = (action: RobotAction): ActionDefinition => {
  return ACTION_REGISTRY[action] || ACTION_REGISTRY.wave;
};

export const getAllActions = (): ActionDefinition[] => {
  return Object.values(ACTION_REGISTRY);
};

export const getActionsByCategory = (category: ActionDefinition['category']): ActionDefinition[] => {
  return Object.values(ACTION_REGISTRY).filter((a) => a.category === category);
};
